name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    hostname: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001/tcp"
    volumes:
      - /srv/appdata/uptime-kuma/data:/app/data
    networks:
      - uptime-kuma_net

networks:
  uptime-kuma_net:
    name: uptime-kuma_net